### ISSUE TITLE
Interfaces for SMB sink(s)

### ISSUE THREAD

**Issue by clairemcginty** [spotify/beam#2]
Belongs to https://github.com/spotify/beam/issues/1

Write an interface/abstract class for sinks and sources. (The first implementation of these would be for Avro.) some considerations I can think of are:

- Require a parameterized PCollection element type required to write to a sink (i.e. `KV<Bucket, List<T>>` to represent a bucket, if we require each bucket to fit in memory)
- Is the type of `Bucket` (from above ^) always an Integer or should we make it a generic
- Whether to implement these as a plain `PTransform`/`DoFn`s or extend `FileBasedSink`/`FileBasedSource`/`OffsetBasedSource` (*if* each bucket is represented as a single PCollection element, like above, runner-determined splitting should be ok...)
- Each implementation of Sink should specify how to write SMB metadata into the file (i.e. # of buckets/hash fn/whatever) so the Source can confirm all sources are compatible at read time
- Give the user flexibility to increase # buckets as time goes on/support multiple files for a single bucket/read asymmetrically sized sources (i.e., source1 and source2 have the same bucketing function but source1 has 4 files and source2 has 16).
- SMB join can read from 2+ sources. do we want to make this number dynamic to read an arbitrary # of sources with their own element types (I think Java's type system would make this really unpleasant), or support fixed #s of sources for an SMB join
- Can we make it possible to re-use existing Beam file write transforms (at the individual file granularity...for example `AvroWriter`) within the SMB sink? A lot of those are package private in the Beam io package so maybe not.

**Comment by nevillelyh** [comment]
Some thoughts:

For `PCollection` type, what about something like `KV<BucketId, T>`, i.e. without grouping them to `List<T>`? That way buckets doesn't have to fit in memory (they'll become lazy `Iterable<T>` after grouping).

Looks like `FileBasedSink` abstracts away sharding and file name handling. Can it do what we want, e.g. custom sharding by bucket ID and custom file naming `output-$bucketId-part-$x-of-$y`? Otherwise we might have to use a custom `PTransform`. Downside of that is we have to implement fault-tolerance, window handling, etc. ourselves.

Should we standardize the metadata format? It could be like the Hadoop `_success` file, written only after all buckets are successfully written, implemented as a separate transform following the `PTransform` that writes the individual buckets.

For source type safety, we probably need something like `TupleTag<T>` hack to retain individual source type, but treat everything as `Object`, generic Avro, etc. under the hood?

**Comment by clairemcginty** [comment]
I think™️  `FileBasedSink` would work if we're saving a grouped `PCollection<BucketId, Iterable<T>>` since `DynamicDestinations` supports value-dependent `DestinationT`s for writes and a custom filename policy per `DestinationT`. I'll have to do some verification to check on the per-bucket sharding, though... I'm hoping it works out since `FileBasedSink` does have those nice properties we wouldn't get for free with a plain `PTransform`.

I like the idea of standardized metadata format! I will add a ticket for implementing a serializable,  comparable bucket metadata format that stores bucket count, key fn, partitioning fn (maybe we could assign each partitioning function implementation a unique URN like Beam does for transforms/coders? 🤷‍♀️) 

makes sense re: `TupleTag<T>` if we're allowing a dynamic number of sources to join. Otherwise we could do something like Scio's `MultiJoin` where we manually implement typed joins for different numbers of sources. we also have to think about whether the merge function itself (#3) can be generalized to a dynamic # of sources.

**Comment by nevillelyh** [comment]
Talked a little IRL. Summary:

Looks like we'll need a custom `PTransform`.
- Given a key function `T => K`
- `GBK` a `PCollection<T>` to `PCollection<KV<BucketT, Iterable<T>>`, where `BucketT` is based on `K` and likely an `int`
- Sort `Iterable<T>` by `K`, spill to disk if necessary
- Write each bucket to a file

Configuration, which should be stored in 1 file per sink
- key function
- hash function
- number of buckets, probably a power of 2 to simplify expanding / shrinking and mixing

**Comment by Illedran** [comment]
I came to the same conclusion but have two `PTransforms`, one for bucketing+sorting and one for writing the data. Respectively:
- Key function: https://github.com/Illedran/scio_smbjoin/blob/master/src/main/java/smbjoin/beam/SMBPartitioning.java#L16
- GBK: https://github.com/Illedran/scio_smbjoin/blob/master/src/main/java/smbjoin/beam/MBShuffle.java#L37
- Sort: (the next line from the previous link)
- Write each bucket to a file: https://github.com/Illedran/scio_smbjoin/blob/master/src/main/java/smbjoin/beam/SMBAvroSink.java#L38
